### PR TITLE
Update/pages - Profile, Bookmarks, Explore

### PR DESCRIPTION
**Pull request by abhij1607**
This PR consists of

- proper post displayed in explore page
- proper post displayed in explore profile page
- proper post displayed in explore bookmarks page

### Note
- ignore previous commits, raised different PR for it, **_just check after [Merge branch 'dev' into feat/filters]_**

### CODE REVIEW

**Review by shivanigangadharan — APPROVED** [review]
Code looks good, bookmarks functionality working well in preview.
Profile and explore page also implemented nicely. 👍🏼

**Comment by hussiantabha** [comment]
Everything works fine, looks neat. Good job

**Review by prachi-sahani — COMMENTED** [review]
Overall the code is clean and easy to understand
Good to merge

**Review by Kavita539 — APPROVED** [review]
- Code looks clean, modular and understandable
- Functionality is implemented nicely and working well
- Overall looks good and can be merged

**Pull request merged**
